version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: jobconnect
      MYSQL_USER: user
      MYSQL_PASSWORD: userp 
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  zookeeper: 
    image: confluentinc/cp-zookeeper:7.0.1 
    restart: always 
    environment: 
      ZOOKEEPER_CLIENT_PORT: 2181 
      ZOOKEEPER_TICK_TIME: 2000 
    ports: 
      - "2181:2181"
      
      
  kafka: 
    image: confluentinc/cp-kafka:7.0.1 
    restart: always 
    depends_on: 
      - zookeeper 
    environment: 
      KAFKA_BROKER_ID: 1 
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181 
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092 
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1 
    ports: 
      - "9092:9092"
      
  redis: 
    image: redis:6 
    restart: always 
    ports: 
      - "6379:6379"


volumes:
  mysql_data:

              